apiVersion: v1
kind: Service
metadata:
  name: adminapi-service  # Name of the service, it will be used by other pods to connect to adminapi
spec:
  selector:
    app: adminapi  # The label selector that matches the pods of your Admin API
  ports:
    - protocol: TCP
      port: 5000  # The port you want the service to listen on
      targetPort: 443  # The port that the Admin API container is running on
  type: ClusterIP  # Change to NodePort or LoadBalancer if you need external access
