apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapi
  labels:
    app: adminapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminapi
  template:
    metadata:
      labels:
        app: adminapi
    spec:
      containers:
      - name: adminapi
        image: kiroto/adminapi:latest  # Docker image
        ports:
        - containerPort: 443
        volumeMounts:
        - name: ssl-certificates
          mountPath: /app/certs  # Certs mount inside the container
          readOnly: true
        env:
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-host

        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-database

        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username

        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password

        - name: MONGO_AUTH_SOURCE
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-auth-source
      volumes:
      - name: ssl-certificates
        secret:
          secretName: ssl-certificates
