apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientapi
  labels:
    app: clientapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientapi
  template:
    metadata:
      labels:
        app: clientapi
    spec:
      containers:
      - name: clientapi
        image: kiroto/clientapi:latest  # Docker image
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: ssl-certificates
          mountPath: /app/certs  # Certs mount inside the container
          readOnly: true
        env:
        - name: ADMIN_API_URL
          value: "https://adminapi-service:5000"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0" # THIS IS UNSAFE IN PRODUCTION. WE SHOULD REJECT UNAUTHORIZED SSL CERTS
      volumes:
      - name: ssl-certificates
        secret:
          secretName: ssl-certificates
